name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: "7-2018-q2"

    - name: Use ccache with arm-gcc
      run: |
        /usr/bin/sh -xc ln -s /usr/bin/ccache /usr/local/bin/arm-none-eabi-gcc
        /usr/bin/sh -xc ln -s /usr/bin/ccache /usr/local/bin/arm-none-eabi-g++
        which arm-none-eabi-gcc
        ccache -s
        arm-none-eabi-gcc --version

    - name: build 
      run: |
        make all_expect_no_limits_fw

    - name: Show ccache stats
      run: |    
        ccache --show-stats

    - name: Upload file
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: |
          package/*
